---

- name: install & update requirement.txt
  with_items: "{{ target }}"
  shell: cd {{ item.path }} && source {{ item.file.split('.') | first }}/bin/activate && pip3 install -r requirements.txt
  args:
    executable: /bin/bash