---
target: 
  - path: "/home/natan/Documents/myproject/config-management/projectone"
    file: "project-a.txt"
  - path: "/home/natan/Documents/myproject/config-management/projecttwo"
    file: "project-b.txt"
  - path: "/home/natan/Documents/myproject/config-management/projectthree"
    file: "project-c.txt"

