---

# - name: "Set variables"
#   set_fact:
#     path_ansible: "/home/ansible/sample-dir"
#     path_local: "/home/natan/sample-dir"
    
- name: clone the Requirement files
  ansible.builtin.git:
    repo: git@github.com:personal-natan/venv-projects.git
    dest: sample-dir
    # single_branch: yes
    clone: yes
    version: master
    
- name: Copy file
  ansible.builtin.copy:
# the ENV updates are stored in ${{ env.GITHUB_WORKFLOW }}, check github-workflow yaml  
 
    ## this below setup is a path in private github runner
    # src: /home/ansible/sample-dir/projects

    ## this below setup is a path in default runner in github
    src: /home/runner/work/config-management/config-management/projects

    remote_src: yes
    dest: "{{ target }}"

# list files only
- name: Listing Project
  shell: ls -pr "{{ target }}"/projects | grep -v /
  register: location

- name: install venv in selected project
  with_items: "{{ location.stdout_lines }}"
  shell: cd "{{ target }}"/projects && python3 -m venv {{ item.split('.') | first }}

- name: install & update requirement.txt
  with_items: "{{ location.stdout_lines }}"
  shell: cd "{{ target }}"/projects && source {{ item.split('.') | first }}/bin/activate && pip install -r {{ item }}
  args:
    executable: /bin/bash

- name: remove unused folder
  shell: rm -rf /home/ansible/sample-dir
