---

# - name: "Set variables"
#   set_fact:
#     path_ansible: "/home/ansible/sample-dir"
#     path_local: "/home/natan/sample-dir"
    
- name: Example clone of a single branch
  ansible.builtin.git:
    repo: git@github.com:personal-natan/venv-projects.git
    dest: /home/ansible/sample-dir
    # single_branch: yes
    clone: yes
    version: master
    
- name: Copy file
  ansible.builtin.copy:
    src: /home/ansible/sample-dir/projects/
    dest: "{{ target }}"

# list files only
- name: Listing Project
  shell: ls -pr "{{ target }}" | grep -v /
  register: location

- name: install venv in selected project
  with_items: "{{ location.stdout_lines }}"
  shell: cd {{ target }} && python3 -m venv {{ item.split('.') | first }}

- name: install & update requirement.txt
  with_items: "{{ location.stdout_lines }}"
  shell: cd {{ target }} && source {{ item.split('.') | first }}/bin/activate && pip install -r {{ item }}
  args:
    executable: /bin/bash
