---

# - name: "Set variables"
#   set_fact:
#     path_ansible: "/home/ansible/sample-dir"
#     path_local: "/home/natan/sample-dir"
    
- name: clone the Requirement files
  ansible.builtin.git:
    repo: git@github.com:personal-natan/venv-projects.git
    dest: sample-dir
    # single_branch: yes
    clone: yes
    version: master
    
# - name: Copy file
#   ansible.builtin.copy:
#     src: sample-dir/projects/
#     remote_src: yes
#     dest: "{{ target }}"
- name: Copy file
  shell: cp -r /home/ansible/sample-dir/projects {{ target }}

# list files only
- name: Listing Project
  shell: ls -pr "{{ target }}" | grep -v /
  register: location

- name: install venv in selected project
  with_items: "{{ location.stdout_lines }}"
  shell: cd {{ target }} && python3 -m venv {{ item.split('.') | first }}

- name: install & update requirement.txt
  with_items: "{{ location.stdout_lines }}"
  shell: cd {{ target }} && source {{ item.split('.') | first }}/bin/activate && pip install -r {{ item }}
  args:
    executable: /bin/bash
