---
- name: Example clone of a single branch
  ansible.builtin.git:
    repo: git@github.com:Natannegara/venv-projects.git
    dest: temp/
    single_branch: yes
    version: master

- name: Copy file
  ansible.builtin.copy:
    src: temp/projects/
    dest: "{{ target }}"

- name: Listing Project
  shell: ls "{{ target }}"
  register: location

- name: install venv in selected project
  with_items: "{{ location.stdout_lines }}"
  shell: cd {{ target }} && python3 -m venv {{ item.split('.') | first }}

- name: install & update requirement.txt
  with_items: "{{ location.stdout_lines }}"
  shell: cd {{ target }} && source {{ item.split('.') | first }}/bin/activate && pip3 install -r {{ item }}
  args:
    executable: /bin/bash