name: pipeline-ansible
on:
  workflow_dispatch:
  push:
    branches:
      - 'master'

jobs:
  # Run the job only with "docs_changed" equals "True"
  running-ansible-script:
    runs-on: 'ubuntu-20.04'
    env:
      dest: roles/install-dep/templates/
      src: venv-project/projects/templates/*
    steps:
    - name: Checkout to venv-project
      uses: actions/checkout@v2
      with:
        repository: Natannegara/venv-projects
        path: .github/projects/templates
        token: ${{ secrets.REPO_TOKEN }}        
    
    - run: mv .github venv-project

    - uses: actions/checkout@v3 
    - run: |
        ls -alh
        echo "now check venv-project"
        ls -alh venv-project
  
      

    # - uses: .github/actions/venv-projects

    # - name: Install venv's Dependencies
    #   run: ansible-playbook install-dep.yml