name: pipeline-ansible
on:
  workflow_dispatch:
  push:
    branches:
      - 'master'

jobs:
  # Run the job only with "docs_changed" equals "True"
  running-ansible-script:
    runs-on: 'ubuntu-20.04'
    steps:
    - name: Checkout to venv-project
      uses: actions/checkout@v2
      with:
        repository: Natannegara/venv-projects
        path: .github/projects/templates
        token: ${{ secret.REPO_TOKEN }}        
    
    - uses: .github/actions/venv-projects
      name: Install venv's Dependencies
      run: |
        ls -al
#        ansible-playbook install-dep.yml