name: pipeline-ansible
on:
  workflow_dispatch:
  push:
    branches:
      - 'master'

jobs:
  # Run the job only with "docs_changed" equals "True"
  install_dependencies:
    runs-on: 'ubuntu-20.04'
    needs: [ checking_template_update ]
    if: needs.checking_template_update.outputs.docs_changed == 'True'
    steps:
    - name: Run Playbook
      run: ansible-playbook install-dep.yml