name: pipeline-ansible
on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - 'master'

jobs:
  # Run the job only with "docs_changed" equals "True"
  pull_venv_project:
    runs-on: 'ubuntu-20.04'
    steps:

# get update of VENV in another repository    
    - name: Checkout to venv-project
      uses: actions/checkout@v2
      with:
        repository: Natannegara/venv-projects
        path: .github/projects/
        token: ${{ secrets.REPO_TOKEN }}

# store the VENV update into artifact
    - uses: actions/upload-artifact@v3
      with:
        name: venv-project-artifact
        path: .github/projects/
        
  pull_config_management:
    runs-on: 'ubuntu-20.04'
    needs: [ pull_venv_project ]

# set github action env
    env:
      dest: roles/install-dep/
      src: venv-project-artifact/*

    steps:
# download ansible script    
    - uses: actions/checkout@v3 
      name: Download Ansible script

# download artifact to ansible configuration folder
    - uses: actions/download-artifact@v3
      name: Download Artifact
      with:
        name: venv-project-artifact
        ## path: ${{ runner.temp }}
        path: ${{ env.GITHUB_WORKFLOW }}

    - name: check after
      run: |
        echo "after"
        ls -alh ${{ env.GITHUB_WORKFLOW }}

# run the ansible to execute the latest update  
    # - name: Install venv's Dependencies
    #   run: ansible-playbook install-dep.yml