name: pipeline-ansible
on:
  workflow_dispatch:
  push:
    branches:
      - 'master'

jobs:
  # Run the job only with "docs_changed" equals "True"
  pull_venv_project:
    runs-on: 'ubuntu-20.04'
    steps:
    - name: Checkout to venv-project
      uses: actions/checkout@v2
      with:
        repository: Natannegara/venv-projects
        path: .github/projects/templates
        token: ${{ secrets.REPO_TOKEN }}

    - uses: actions/upload-artifact@v3
      with:
        name: venv-project-artifact
        path: .github/projects/
        
  pull_config_management:
    runs-on: 'ubuntu-20.04'
    needs: [ pull_venv_project ]
    env:
      dest: roles/install-dep/templates/
      # src: venv-project-artifact/*
    steps:
    - uses: actions/download-artifact@v3
      name: Download Artifact
      with:
        name: venv-project-artifact
        # path: ${{ runner.temp }}
        path: ${{ env.GITHUB_WORKFLOW }}

    - uses: andstor/copycat-action@v3
      name: Copy artifact to ansible repo
      with:
        personal_token: ${{ secrets.REPO_TOKEN }}
        src_path: "${{ env.GITHUB_WORKFLOW }}/templates/projects/"
        dst_path: roles/install-dep/templates/
        dst_owner: Natannegara
        dst_repo_name: config-management

    - uses: actions/checkout@v3 
      name: pull ansible repo

    - run: |
        echo "pull main repo"
        ls -alh
        ls -alh roles/install-dep/templates/
  
    # - name: Install venv's Dependencies
    #   run: ansible-playbook install-dep.yml